### ISSUE TITLE
Pageviews not tracking, only visitors

### ISSUE THREAD

**Issue by garridovaz** [dancameron/server-side-google-analytics#5]
Hi there! First of all thanks for sharing this nice and simple library for server-side GA. 

I do have one question. When I trigger the following code:

```php
$ssga->set_page( '/calls/Education_level.php' );
$ssga->set_page_title( 'Education Level' );
$ssga->send();
$ssga->reset();
```

Each page view gets tracked as a separate visitor, and the page view count remains at zero.  So instead of having a bunch of page views triggered for the pages I have set in the code, I get a number of online visitors. Am I doing something wrong? GA even shows the correct pages in the "Active Pages" tables, but no page views to those pages are registered.

**Comment by djkad** [comment]
Is possible to put an example of Ecommerce tracking???

**Comment by nczz** [comment]
@djkad check it out https://github.com/nczz/Server-Side-PHP-Google-Analytice

update this repository (thanks @dancameron )and test Ecommerce tracking well.

**Comment by dancameron** [comment]
Please submit a Pull Request.

**Comment by nczz** [comment]
@dancameron Done!

**Comment by dancameron** [comment]
Excellent.
